
services:
  backend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.backend
    container_name: farmzyy_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app/ml_models:/app/app/ml_models
    restart: always
